import { Footer } from "@/components/Footer";
import { Sidebar } from "@/components/Sidebar";
import "./globals.css";

export const metadata = {
  title: "Web Radio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="h-screen flex flex-col bg-zinc-900 text-zinc-50">
        <div className="flex flex-1">
          <Sidebar />
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
