import { ProfileCard } from "@/components/ProfileCard";

export const metadata = {
  title: "Web Radio | Equipe",
  description: "Generated by create next app",
};

export default function Members() {
  return (
    <main className="flex-1 p-6">
      <h1 className="text-3xl font-semibold">Nossa Equipe</h1>

      <div className="h-full flex justify-center items-center flex-row flex-wrap gap-8 py-12">
        <ProfileCard name="Jack Fahrer" image="/img/teste.jpeg" />
        <ProfileCard name="Magosso" image="/img/teste2.jpeg" />
        <ProfileCard name="Dudu" image="/img/teste3.jpeg" />
        <ProfileCard name="Luis Fernando" image="/img/member5.jpeg" />
        <ProfileCard name="Leandro" image="/img/teste5.jpeg" />
        <ProfileCard name="Fabinho Rezende" image="/img/teste6.jpeg" />
        <ProfileCard name="Luiz Domingues" image="/img/teste7.jpeg" />
        <ProfileCard name="Julião" image="/img/teste8.jpeg" />
      </div>
    </main>
  );
}
